name: CI/CD Pipeline - Build & Deploy to ACR & AKS

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and Test
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --configuration Release --no-restore --verbosity normal

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ secrets.ACR_LOGIN_SERVER }}/simpleaksapi:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Save Docker Image Tag
        run: echo "IMAGE_TAG=${{ secrets.ACR_LOGIN_SERVER }}/simpleaksapi:${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to Stage
        run: |
          helm upgrade --install simpleaksapi-stage ./helm-chart \
            --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/simpleaksapi \
            --set image.tag=${{ github.sha }} \
            --set environment=stage \
            --namespace stage \
            --create-namespace

      - name: Deploy to Prod (only on main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install simpleaksapi-prod ./helm-chart \
            --set image.repository=${{ secrets.ACR_LOGIN_SERVER }}/simpleaksapi \
            --set image.tag=${{ github.sha }} \
            --set environment=prod \
            --namespace prod \
            --create-namespace
