name: CI/CD - Build & Push to ACR and Run Test Container

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ secrets.ACR_LOGIN_SERVER }}/simpleaksapi:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  test-container:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Pull Image from ACR
        run: |
          docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker pull ${{ env.IMAGE_TAG }}

      - name: Run Container Locally
        run: |
          docker run -d -p 8080:8080 --name simpleaksapi-test-container ${{ env.IMAGE_TAG }}

      - name: Wait for Container to Start
        run: sleep 5

      - name: Test Container Health Endpoint
        run: |
          curl --fail http://localhost:8080/health || (docker logs simpleaksapi-test-container && exit 1)

      - name: Stop and Remove Test Container
        run: |
          docker stop simpleaksapi-test-container
          docker rm simpleaksapi-test-container
